const lyricsList = [
    {
    lyric: "I wonder how I got by this week,\n I only touched you once",
    song: "Void",
    artist: "The Neighbourhood",
    album: "Hard to Imagine the Neighbourhood Ever Changing",
    year: "2018",
    bgColor: "#402617",
    textColor: "#EBE7E6",
    albumCover: "images/nbhd.jpg",
    },
    {
    lyric: "When you're far away, I still feel it all the same",
    song: "Heavenly",
    artist: "Cigarettes After Sex",
    album: "Cry",
    year: "2019",
    bgColor: "#353535",
    textColor: "#A4A4A4",
    albumCover: "images/cry.jpg",
    },
    {
    lyric: "I'm useless when you're stuck in my mind,\n I've been foolish, think of you all the time",
    song: "Useless",
    artist: "Omar Apollo",
    album: "Apolonio",
    year: "2020",
    bgColor: "#9C91BB",
    textColor: "#694233",
    albumCover: "images/apolonio.jpg",
    },
    {
    lyric: "I don't wanna look at anything else now that I saw you",
    song: "Daylight",
    artist: "Taylor Swift",
    album: "Lover",
    year: "2019",
    bgColor: "#FEB2D9",
    textColor: "#610A2C",
    albumCover: "images/lover.jpg",
    },
    {
    lyric: "I get so lost inside your eyes...\n Would you believe it?",
    song: "Adore You",
    artist: "Harry Styles",
    album: "Fine Line",
    year: "2019",
    bgColor: "#8CD5E3",
    textColor: "#A5566C",
    albumCover: "images/fineline.jpg",
    },
    {
    lyric: "If you hold me without hurting me,\n you'll be the first who ever did",
    song: "Cinnamon Girl",
    artist: "Lana del Rey",
    album: "Norman Fucking Rockwell!",
    year: "2019",
    bgColor: "#748FAD",
    textColor: "#CD191E",
    albumCover: "images/nfr.jpg",
    },
    {
    lyric: "I may not know a lot of things but\n I know that we're surefire",
    song: "Surefire",
    artist: "John Legend",
    album: "DARKNESS AND LIGHT",
    year: "2016",
    bgColor: "#fff",
    textColor: "#575757",
    albumCover: "images/dal.jpg",
    },
    {
    lyric: "If you could see my thoughts,\n you would see our faces",
    song: "Ivy",
    artist: "Frank Ocean",
    album: "Blonde",
    year: "2016",
    bgColor: "#51754F",
    textColor: "#E3E3E5",
    albumCover: "images/blonde.jpg",
    },
    {
    lyric: "You could absolutely break my heart,\n that's how I know that we're in love",
    song: "We're In Love",
    artist: "boygenius",
    album: "the record",
    year: "2023",
    bgColor: "#6B8986",
    textColor: "#A04123",
    albumCover: "images/therecord.jpg",
    },
    {
    lyric: "You're the star I look for every night,\n when it's dark you'll stick right by my side",
    song: "Compass",
    artist: "The Neighbourhood",
    album: "Hard to Imagine the Neighbourhood Ever Changing",
    year: "2018",
    bgColor: "#402617",
    textColor: "#EBE7E6",
    albumCover: "images/nbhd.jpg",
    },
    {
    lyric: "Even the moonlight through the window looks like you",
    song: "Twilight",
    artist: "LOONA",
    album: "Kim Lip",
    year: "2017",
    bgColor: "#9557A1",
    textColor: "#F2DC79",
    albumCover: "images/kimlip.jpg",
    },
    {
    lyric: "I will see your body bare\n and still I will live here",
    song: "I Will",
    artist: "Mitski",
    album: "Bury Me At Makeout Creek",
    year: "2014",
    bgColor: "#FEFEFE",
    textColor: "#2A4551",
    albumCover: "images/buryme.jpg",
    },
    {
    lyric: "So pretty that you kill me softly",
    song: "Archetype",
    artist: "Omar Apollo",
    album: "Ivory (Marfil)",
    year: "2022",
    bgColor: "#635C54",
    textColor: "#fefefe",
    albumCover: "images/ivory.jpg",
    },
    {
    lyric: "I've dreamt about you nearly\n every night this week",
    song: "Do I Wanna Know?",
    artist: "Arctic Monkeys",
    album: "AM",
    year: "2013",
    bgColor: "#021011",
    textColor: "#fff",
    albumCover: "images/am.jpg",
    },
    {
    lyric: "To me you are everything,\n even though in this world we are zero",
    song: "Zero",
    artist: "Mahmood",
    album: "Ghettolimpo",
    year: "2021",
    bgColor: "#C68151",
    textColor: "#F0F1F3",
    albumCover: "images/ghettolimpo.jpg",
    },
    {
    lyric: "Please make room in your heart for me to rest",
    song: "ONLY",
    artist: "LeeHi",
    album: "4 ONLY",
    year: "2021",
    bgColor: "#AFC9D0",
    textColor: "#54686D",
    albumCover: "images/only.jpg",
    },
    {
    lyric: "The universe is ours\n but you're my favorite part",
    song: "KISS ME",
    artist: "DPR LIVE",
    album: "IS ANYBODY OUT THERE?",
    year: "2020",
    bgColor: "#C13A16",
    textColor: "#F2CDBE",
    albumCover: "images/dpr.jpg",
    },
    {
    lyric: "I want to breathe you in like a vapor,\n I want to be the one you remember",
    song: "Vapor",
    artist: "5 Seconds of Summer",
    album: "Sounds Good Feels Good",
    year: "2015",
    bgColor: "#FF3A85",
    textColor: "#FEEF30",
    albumCover: "images/sgfg.jpg",
    },
    {
    lyric: "Floating through the night feels like we're dancing,\nis this the feeling of falling in love?",
    song: "If I Got You",
    artist: "ZAYN",
    album: "Icarus Falls",
    year: "2018",
    bgColor: "#6AB2FD",
    textColor: "#131836",
    albumCover: "images/icarus.jpg",
    },
    {
    lyric: "You make me happy,\nyou make my soul smile",
    song: "Love Between...",
    artist: "Kali Uchis",
    album: "Red Moon in Venus",
    year: "2023",
    bgColor: "#B6250E",
    textColor: "#EAD09B",
    albumCover: "images/rmiv.png",
    },

  ];

  
